# Generated by Django 3.0.4 on 2020-03-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskLists', '0002_auto_20200328_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MODERATE', 'MODERATE'), ('LOW', 'LOW')], max_length=10),
        ),
    ]
