# Generated by Django 3.0.4 on 2020-03-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskLists', '0003_auto_20200328_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='to_be_done_date',
            field=models.DateField(null=True),
        ),
    ]
