# Generated by Django 3.0.4 on 2020-03-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskLists', '0004_auto_20200328_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='ordered_by',
            field=models.CharField(choices=[('date_created up', 'Date up'), ('date_created down', 'Date downscending'), ('priority up', 'Priority ascending '), ('priority down', ' Priority downscending'), ('to_be_done_date up', 'Done date ascending'), ('to_be_done_date down', 'Done date downscending'), ('is_done up', 'Finished'), ('is_done down', 'Not finished')], default='date_created up', max_length=120),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'HIGH'), ('2', 'MODERATE'), ('3', 'LOW')], max_length=10),
        ),
    ]
