# Generated by Django 3.0.4 on 2020-03-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskLists', '0005_auto_20200330_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='ordered_by',
            field=models.CharField(choices=[('date_created', 'Date up'), ('-date_created', 'Date downscending'), ('priority', 'Priority ascending '), ('-priority', ' Priority downscending'), ('to_be_done_date', 'Done date ascending'), ('-to_be_done_date', 'Done date downscending'), ('is_done', 'Finished'), ('-is_done', 'Not finished')], default='date_created up', max_length=120),
        ),
    ]
